import { StyleSheet } from "react-native";
import { Theme } from "@/constants/colors";

export const createStyles = (theme: Theme) => {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: theme.background,
    },
    container: {
      flex: 1,
      backgroundColor: theme.background,
    },
    scrollView: {
      flex: 1,
    },
    header: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      zIndex: 10,
      elevation: 10,
      justifyContent: "flex-end",
    },
    headerContent: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 16,
      height: 48, // HEADER_CONTENT_HEIGHT
    },
    headerTitle: {
      fontSize: 24,
      fontWeight: "bold",
    },
    contentContainer: {
      paddingTop: 48, // Same as HEADER_CONTENT_HEIGHT
      paddingHorizontal: 16,
    },
    shieldContainer: {
        alignItems: "center", // Horizontally center the content
        paddingHorizontal: 16,
        marginTop: 8,
        marginBottom: 24,
      },
    shieldGradient: {
        borderRadius: 16,
        overflow: "hidden",
    },
    shieldCard: {
        borderRadius: 20,
        padding: 24,
        alignItems: "center",
        justifyContent: "center",
        elevation: 8,
        shadowColor: theme.shadow,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        overflow: "hidden",
      },
    shieldSettingsButton: {
        position: "absolute",
        top: 16,
        right: 16,
        zIndex: 1,
    },
    shieldButton: {
      width: 200,
      height: 200,
      borderRadius: 100,
      justifyContent: "center",
      alignItems: "center",
      elevation: 8,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
    },
    shieldIcon: {
        marginBottom: 16,
    },
    shieldText: {
        fontSize: 22,
        fontWeight: "bold",
        marginTop: 16,
    },
    shieldDescription: {
        fontSize: 14,
        opacity: 0.8,
        textAlign: "center",
        marginTop: 8,
    },
    shieldStatusText: {
      marginTop: 16,
      fontSize: 18,
      fontWeight: "600",
    },
    timerContainer: {
        marginTop: 30,
        marginHorizontal: 10,
        borderRadius: 16,
        borderWidth: 1,
        padding: 16,
    },
    timerHeader: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 10,
    },
    timerTitle: {
        fontSize: 16,
        fontWeight: "600",
        marginLeft: 8,
    },
    switch: {
        marginLeft: "auto",
    },
    timerOptions: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "flex-start",
        marginTop: 15,
        paddingHorizontal: 15,
    },
    timerOptionWrapper: {
        flexDirection: "row",
        alignItems: "center",
        margin: 5,
    },
    timerOption: {
        paddingVertical: 8,
        paddingHorizontal: 15,
        borderRadius: 20,
        borderWidth: 1,
    },
    timerOptionText: {
        fontSize: 14,
        fontWeight: "bold",
    },
    deleteButton: {
        marginLeft: -10,
        padding: 5,
        zIndex: 1,
    },
    customTimerContainer: {
        flexDirection: "row",
        alignItems: "center",
        marginTop: 15,
        paddingHorizontal: 20,
    },
    customTimerInput: {
        flex: 1,
        height: 40,
        borderRadius: 8,
        paddingHorizontal: 10,
        marginRight: 10,
        borderWidth: 1,
    },
    addButton: {
        paddingHorizontal: 15,
        height: 40,
        justifyContent: "center",
        alignItems: "center",
        borderRadius: 8,
    },
    addButtonText: {
        fontWeight: "bold",
    },
    timerText: {
      fontSize: 16,
      color: theme.subtext,
    },
    controlsContainer: {
      flexDirection: "row",
      justifyContent: "space-around",
      alignItems: "center",
      padding: 16,
      backgroundColor: theme.card,
      borderRadius: 16,
      marginHorizontal: 16,
      marginBottom: 16,
    },
    controlGroup: {
      alignItems: "center",
    },
    controlLabel: {
      fontSize: 12,
      color: theme.subtext,
      marginBottom: 8,
    },
    durationSelector: {
      flexDirection: "row",
      alignItems: "center",
    },
    durationText: {
      fontSize: 16,
      fontWeight: "bold",
      color: theme.text,
      marginHorizontal: 8,
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: "600",
      marginLeft: 8,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      paddingVertical: 32,
    },
    nowPlayingContainer: {
        marginBottom: 24,
    },
    sectionHeader: {
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 16,
        marginBottom: 12,
    },
    loader: {
        marginLeft: "auto",
    },
    refreshButton: {
        marginLeft: "auto",
    },
    noMusicContainer: {
        padding: 24,
        alignItems: "center",
        justifyContent: "center",
    },
    noMusicText: {
        fontSize: 14,
        marginTop: 8,
    },
    recentContainer: {
        marginBottom: 8,
    },
    showCustomButton: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        marginTop: 15,
        padding: 10,
        marginHorizontal: 20,
        borderRadius: 8,
        borderWidth: 1,
    },
    showCustomButtonText: {
        fontWeight: "bold",
        marginLeft: 10,
    },
    batchExcludeButton: {
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 16,
        marginLeft: "auto",
    },
    batchExcludeText: {
        fontSize: 12,
        fontWeight: "bold",
        marginLeft: 4,
    },
    progressContainer: {
        marginHorizontal: 20,
        marginBottom: 16,
        padding: 16,
        borderRadius: 12,
        borderWidth: 1,
    },
    progressHeader: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 12,
    },
    progressText: {
        fontSize: 14,
        fontWeight: "600",
        marginLeft: 8,
    },
    progressBarContainer: {
        flexDirection: "row",
        alignItems: "center",
    },
    progressBar: {
        flex: 1,
        height: 8,
        borderRadius: 4,
        marginRight: 12,
        overflow: "hidden",
    },
    progressBarFill: {
        height: "100%",
        borderRadius: 4,
    },
    progressCount: {
        fontSize: 12,
        fontWeight: "500",
        minWidth: 40,
        textAlign: "right",
    },
    selectionModeContainer: {
        position: "absolute",
        left: 0,
        right: 0,
        height: 56,
        backgroundColor: "#2D2D34",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 16,
        borderTopWidth: 1,
        borderTopColor: "rgba(255,255,255,0.1)",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: -3 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 20,
    },
    selectionText: {
        fontSize: 16,
        fontWeight: "600",
        marginRight: 12,
    },
    selectionButton: {
        paddingVertical: 10,
        paddingHorizontal: 24,
        borderRadius: 20,
        justifyContent: "center",
        alignItems: "center",
    },
    selectionButtonText: {
        fontSize: 15,
        fontWeight: "bold",
    },
    selectionCancelButton: {
        padding: 4,
        marginLeft: 12,
    },
    selectAllRow: {
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 10,
        paddingHorizontal: 20,
        marginLeft: "auto"
    },
    selectAllCheckbox: {
        width: 22,
        height: 22,
        borderRadius: 6,
        borderWidth: 2,
        justifyContent: "center",
        alignItems: "center",
        marginRight: 12,
    },
    selectAllText: {
        fontSize: 15,
        fontWeight: "600",
    },
    selectionContainer: {
        position: "absolute",
        bottom: 0,
        left: 0,
        right: 0,
        borderTopWidth: 1,
        paddingHorizontal: 20,
        paddingTop: 10,
    },
    selectionHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 10,
    },
    selectionCount: {
        fontSize: 16,
        fontWeight: "bold",
    },
    selectionActions: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: 10,
    },
    actionButton: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 12,
        borderRadius: 20,
        marginHorizontal: 5,
    },
    actionButtonText: {
        fontSize: 16,
        fontWeight: "bold",
        marginLeft: 8,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.6)",
      justifyContent: "center",
      alignItems: "center",
    },
    modalContent: {
      margin: 20,
      backgroundColor: "white",
      borderRadius: 20,
      padding: 35,
      alignItems: "center",
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 5,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: "bold",
      marginBottom: 15,
    },
    modalOption: {
      width: "100%",
      padding: 15,
      borderTopWidth: 1,
      borderTopColor: "#eee",
    },
    modalOptionText: {
      textAlign: "center",
      fontSize: 18,
    },
    centeredView: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      marginTop: 22,
    },
    modalView: {
      margin: 20,
      backgroundColor: "white",
      borderRadius: 20,
      padding: 35,
      alignItems: "center",
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 5,
    },
    modalText: {
      marginBottom: 15,
      textAlign: "center",
    },
    modalSubText: {
      marginBottom: 15,
      textAlign: "center",
    },
    modalButtons: {
      flexDirection: "row",
      justifyContent: "space-between",
      width: "100%",
    },
    button: {
      borderRadius: 20,
      padding: 10,
      elevation: 2,
    },
    textStyle: {
      color: "white",
      fontWeight: "bold",
      textAlign: "center",
    },
  });
};